#!/bin/sh

echo "hidden file" > .hidden_file
echo "file a" > a.s
echo "file b" > b.s
echo "Alice has a cat" > alice_has_a_cat.txt
echo "test file" > test_file.txt
echo "file with a long name" > "Very long name with spaces.txt"
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur quis urna eu laoreet. Integer id mollis augue, nec egestas quam. Praesent sed sapien orci. Mauris molestie vulputate egestas. Maecenas viverra justo purus, non interdum augue pulvinar a. Phasellus condimentum lectus ut elementum efficitur. Vestibulum massa purus, convallis placerat arcu scelerisque, tempus vehicula mauris. Donec eu nisi nec lacus congue lacinia ut a augue. Curabitur ultricies sollicitudin finibus. Suspendisse lacinia lorem ligula, sit amet venenatis augue eleifend vitae.

Mauris volutpat euismod velit, at molestie augue fringilla sed. Morbi eget gravida libero. Integer eros orci, feugiat ac ipsum a, fermentum lacinia massa. Nullam eu libero ac dui rhoncus sodales. Donec euismod imperdiet lacus, nec sollicitudin nisl congue nec. Vivamus non faucibus metus. Nam vitae varius lectus. Fusce cursus enim ante, ut placerat velit dignissim eu.

Curabitur commodo lacus sed ipsum fringilla rhoncus. Phasellus fringilla dictum dolor eget venenatis. Sed consequat volutpat leo eu vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris in facilisis leo. Aliquam id efficitur leo, sit amet sagittis est. Cras eu felis eget ligula tincidunt pretium. Quisque tempor sapien eget justo pretium, at lacinia metus pretium. Praesent euismod bibendum mauris eget scelerisque. Nunc interdum ante vel quam blandit tempus. Vivamus commodo nibh urna, in posuere turpis molestie ac. Ut gravida leo et tempus aliquam.

Quisque nec ante in tortor scelerisque dapibus. Integer ultricies purus sit amet convallis vulputate. Donec eu accumsan odio. Morbi blandit molestie neque sit amet luctus. Sed sodales justo vel pellentesque ultrices. Vivamus quis urna accumsan, tincidunt ipsum a, elementum nulla. Sed gravida non purus id cursus. Aliquam varius elit eget posuere efficitur. Sed non arcu ac metus pellentesque elementum. Aenean feugiat, nulla vitae molestie cursus, nisi diam imperdiet erat, non lacinia odio libero sit amet massa. Mauris posuere nisi vitae tellus pretium feugiat. Nam feugiat ornare tortor, at pulvinar justo sagittis ac. Pellentesque ipsum turpis, molestie at varius at, porttitor sit amet velit.

Duis finibus quam enim, quis suscipit est euismod eu. Cras et efficitur ante. Phasellus aliquet mi nec massa placerat, eu condimentum dolor facilisis. Nullam pellentesque dui in dolor laoreet, in vulputate mi iaculis. Suspendisse potenti. Pellentesque eget ante eu justo semper pulvinar. Vestibulum vitae mi ex. Quisque enim eros, sodales at ligula sed, luctus vehicula nulla.

Integer aliquam erat sit amet nisi vestibulum, porttitor facilisis est pulvinar. Sed sodales ex aliquam viverra accumsan. Proin orci eros, finibus eget mauris eu, fringilla luctus justo. Sed tempor ex lectus, at efficitur felis tincidunt sed. Aliquam ac turpis id mi suscipit sollicitudin. Aenean et porta eros. Praesent metus nisl, tempor at est maximus, molestie maximus ante. Fusce consequat fermentum pharetra. Nullam non quam rhoncus, congue ex at, elementum metus. Cras sed mollis sem. Nullam sit amet turpis et velit laoreet interdum eget ut diam. Etiam et ligula dapibus, tristique nisl non, pharetra tellus.

Aliquam gravida placerat quam vitae lobortis. Cras sollicitudin tempus turpis, eu gravida ante accumsan eget. Curabitur consectetur magna est, vitae dictum mauris pharetra eu. Sed mattis odio venenatis risus tincidunt, vel ultrices est tincidunt. Sed ut neque ultricies, ultricies orci sed, volutpat quam. Aliquam erat volutpat. Ut ut diam a leo faucibus interdum id quis lectus. Vestibulum hendrerit lobortis tempus. Cras nisi justo, iaculis eu porta non, dapibus vitae tellus. Fusce euismod eu lectus non pellentesque. Donec commodo maximus mauris, quis iaculis arcu eleifend rhoncus. Donec tincidunt ullamcorper felis, sollicitudin facilisis justo faucibus non. Vivamus sit amet quam vel tortor sodales pretium nec sit amet dui.

Vestibulum bibendum purus tellus, bibendum bibendum tellus convallis id. Aliquam in feugiat enim. Ut dapibus ac risus nec mollis. Etiam ultrices risus ac ultrices posuere. Cras tempus nisi eget nibh ornare, sed scelerisque felis lobortis. Vestibulum id ante arcu. Nullam facilisis, nunc pellentesque vehicula elementum, nibh nunc dictum diam, ac semper lectus ex eget orci. Vivamus quis mi urna. Morbi pharetra, lacus ut accumsan pellentesque, urna ipsum iaculis ante, porttitor aliquet neque urna nec nisl. Praesent quis auctor nulla, sed lobortis turpis.

Sed vel lacus sed libero pretium condimentum. In vel lectus nec quam lacinia commodo a id enim. Aenean convallis nisl ipsum, eget egestas augue sagittis nec. Nam laoreet ligula sit amet malesuada viverra. Sed finibus dapibus maximus. Nunc elementum consectetur lorem. Duis consectetur massa arcu, eget imperdiet ipsum tincidunt sit amet. Sed a erat ultricies, efficitur libero quis, condimentum nulla. Nullam pretium, nisi ac lacinia venenatis, ipsum purus volutpat libero, nec posuere turpis turpis eget mauris. Morbi dapibus purus eget justo venenatis, vitae lobortis felis molestie.

In dignissim, justo ut vulputate sollicitudin, mauris tellus cursus lacus, vel sagittis enim eros eget ante. Praesent ac pulvinar enim, id vulputate velit. Etiam blandit lorem eget nisl blandit, vel pellentesque lacus viverra. Phasellus hendrerit consectetur lectus in efficitur. Vestibulum sit amet neque sit amet velit sodales euismod. Sed volutpat ligula urna, quis condimentum neque euismod at. Nulla a enim nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Suspendisse placerat massa sit amet sapien tristique, nec pulvinar odio pharetra. Duis ut risus eget justo semper pulvinar vulputate sit amet orci. Nullam a odio at quam iaculis posuere sed eget est. Interdum et malesuada fames ac ante ipsum primis in faucibus. In et pulvinar quam, pellentesque molestie massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vel magna ac sem ultricies fringilla non ac magna. Duis ac blandit ligula, et sollicitudin risus. Sed varius non neque viverra cursus. Proin lobortis orci non mi elementum, eu euismod urna facilisis. Etiam lacinia ligula sit amet augue ullamcorper, vel pretium massa commodo. Maecenas facilisis magna augue, non euismod velit bibendum non. Phasellus sed risus blandit, tristique nibh sed, gravida justo. Vivamus sed sapien interdum ante rhoncus vestibulum. Sed gravida velit lacus, ut sodales massa pellentesque vel.

Morbi in enim erat. Morbi a tempus nunc. Donec tincidunt, metus eu congue varius, elit justo tincidunt dui, vel aliquam enim sem et nisl. Phasellus eu vulputate ex, eget finibus nisl. Nunc a arcu blandit, convallis ligula vitae, lobortis augue. Etiam bibendum tortor nisl, ut rutrum tortor tristique id. In vel volutpat nisl.

Ut malesuada mauris nec dolor convallis, quis feugiat tellus tincidunt. Suspendisse a ligula at velit lobortis malesuada eget eget sem. Nulla viverra vehicula massa eget porttitor. Nullam iaculis sit amet metus eu tempus. Integer dignissim mollis augue in venenatis. Aliquam erat volutpat. Suspendisse id ipsum lacus. Sed lorem metus, vulputate nec vehicula ac, imperdiet eget lectus. Phasellus fermentum nulla leo, ut dictum lacus blandit vitae. Fusce tempus ornare nunc, ac commodo mi pellentesque sed. Fusce pulvinar, neque eget vehicula feugiat, massa nisl laoreet urna, ac efficitur tellus mauris at massa. Proin dui velit, viverra ut tortor et, egestas vestibulum magna. Aliquam eget tristique quam, rhoncus semper ligula.

Suspendisse ac erat ante. Fusce ut purus aliquam, rhoncus eros malesuada, placerat mauris. Aliquam urna velit, interdum in urna at, hendrerit bibendum leo. Cras et ex ut est venenatis tristique. Quisque malesuada molestie tincidunt. Quisque molestie, velit quis imperdiet viverra, felis est lacinia purus, id pellentesque dui nulla eu turpis. Ut tincidunt, elit id pulvinar placerat, risus quam hendrerit ipsum, quis suscipit diam dui sit amet lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras ac nisl ac mi fermentum euismod. Pellentesque sit amet consequat justo. Maecenas sollicitudin vehicula pellentesque. Proin eget diam maximus nibh fringilla dapibus. Maecenas dolor mauris, faucibus eu elementum non, faucibus eget ligula. Nullam laoreet laoreet faucibus.

Fusce sodales mi at nisi iaculis, a sollicitudin mauris porttitor. Sed id lorem elit. Integer lacinia nunc et turpis porta sodales. Mauris sit amet varius leo. Aliquam blandit sed tortor id elementum. Cras ut quam vel nunc bibendum malesuada ut ut leo. Nunc pulvinar dolor ut massa consectetur, nec tempor turpis vulputate. Praesent congue varius porta. Suspendisse aliquet gravida nulla, at aliquam eros rhoncus eu. Nullam sit amet sollicitudin risus. Duis lectus urna, malesuada nec viverra quis, porttitor sed ex. Proin elementum elit nisl, non placerat mauris ultrices et. Morbi nulla mi, iaculis sed ultrices vitae, elementum eu risus.

Pellentesque tempus magna quam, sed pretium turpis tristique vel. Nulla porta lacinia sollicitudin. Integer nec gravida justo. Nulla non sem sit amet enim lacinia mollis. Nullam justo nulla, porttitor lobortis faucibus ac, dapibus nec urna. Aliquam erat volutpat. Vivamus lorem quam, pharetra sit amet neque et, aliquam tincidunt elit. Praesent id venenatis nisi. Cras in placerat massa. Morbi suscipit metus et bibendum venenatis. Proin semper magna ac semper venenatis. Nunc id egestas sapien, ut pellentesque nulla. Proin varius nulla justo, id ullamcorper lacus molestie et. Vestibulum at lacus metus.

Etiam sit amet dignissim nibh, in ultrices nisi. Aenean mollis metus vel nibh laoreet ullamcorper. Etiam quis ipsum turpis. Donec lobortis sagittis ultricies. Vestibulum ultricies justo eu purus iaculis, convallis semper lectus efficitur. Vivamus euismod fringilla neque, ac ultrices mi pellentesque sit amet. Aliquam a libero quis tellus iaculis consectetur. Proin in nisi in quam imperdiet laoreet eget in magna. Proin metus orci, tempus tempor consectetur id, ullamcorper quis mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Integer justo tortor, porttitor ac mi ut, mattis accumsan nisi. Phasellus tincidunt viverra odio, vulputate feugiat augue faucibus non. Curabitur elementum, sem id elementum faucibus, nibh mi convallis ex, eu mollis risus neque vitae sem. In vel diam quis sapien malesuada ornare ut id dolor. Donec euismod ipsum eu pellentesque lobortis. Suspendisse semper urna vehicula volutpat dictum. Aenean nec ultricies neque. Sed sed nibh ac ligula faucibus facilisis eu ac dolor. Nunc pharetra, nisi quis convallis lacinia, ipsum nulla vestibulum tortor, a sagittis velit orci dignissim lacus. Duis nec ipsum porttitor dolor semper vestibulum. Praesent suscipit euismod varius.

Mauris leo eros, faucibus vel ultricies aliquet, accumsan et felis. Integer elementum erat a sem auctor volutpat. Proin id mollis felis, ac congue massa. Fusce nec sem sit amet sem interdum tempor. Etiam quis nibh dapibus lectus volutpat porttitor at et purus. Suspendisse ut arcu efficitur, commodo ligula rhoncus, pulvinar ex. Etiam gravida arcu vel orci sodales, rutrum vehicula nisl consequat. Duis bibendum, elit vitae placerat interdum, neque leo sagittis nisl, ac sodales eros urna nec eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Praesent lacus magna, aliquet sed nibh vel, eleifend pharetra felis. Quisque bibendum vitae urna id tincidunt. Nam venenatis, dui eu venenatis egestas, urna mi faucibus mauris, sed placerat dui orci ut sapien. Aliquam vitae commodo dui, ut bibendum quam. Etiam quis nulla et nunc mollis auctor. Phasellus laoreet sed lectus eu tincidunt. Curabitur semper elit sed neque elementum aliquam. Praesent eu malesuada elit. Curabitur ut justo ut lectus pellentesque aliquam in vitae diam. Cras non euismod nulla. Cras vel tempus purus, ut volutpat eros. Quisque et pretium nisl, eu gravida leo. Aliquam sit amet maximus nunc.

Aliquam at semper ante. Nunc id condimentum ipsum. Aliquam porta justo et ipsum condimentum lobortis. Curabitur quis semper eros, ut tincidunt sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor ipsum a elementum mattis. Ut vehicula vestibulum augue in porttitor.

Etiam condimentum dapibus lectus, et tempor nisl facilisis eget. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ut elit non dolor vehicula fringilla nec eget nunc. Fusce volutpat ultricies orci. Donec at orci enim. Donec convallis magna non dolor vestibulum, at aliquam sem finibus. Mauris maximus nulla est, eu malesuada magna vehicula quis.

Quisque gravida velit laoreet tellus hendrerit porttitor. Quisque rutrum justo ac mi euismod fringilla. Mauris efficitur vitae enim semper ornare. Vivamus tempus, felis vel dictum varius, lectus ex venenatis ante, et viverra arcu purus efficitur purus. Ut dolor lectus, tempus eget dapibus in, vehicula ac ante. Mauris ante risus, commodo nec efficitur ac, mollis eu justo. Pellentesque eu molestie urna. Sed maximus vulputate velit vitae porttitor. Fusce vitae mauris orci.

Pellentesque eu iaculis velit. Quisque at purus ipsum. Quisque in sem risus. Nullam auctor nec sapien non viverra. Aenean id feugiat ante. Praesent egestas velit diam, pretium fermentum massa rhoncus sit amet. Ut volutpat arcu a tortor auctor, at sodales nunc tincidunt. Sed lobortis nulla quam, non sagittis dolor mattis quis. Sed tempor semper orci eget laoreet. Proin convallis volutpat massa non pharetra.

Phasellus a augue sed ipsum mollis pharetra sed non justo. Proin in erat nec velit tempor congue vitae et lorem. Nulla mattis gravida efficitur. Aliquam placerat risus quis dui malesuada mollis. Mauris nec dolor sit amet urna eleifend suscipit. Fusce gravida orci at nibh pellentesque, sit amet elementum mauris venenatis. Suspendisse finibus erat eget erat faucibus, eget placerat dolor maximus. Integer sollicitudin porta elit, in rhoncus lorem aliquet at. Morbi id urna placerat, pellentesque leo pretium, commodo nibh.

Nulla facilisi. Nulla nunc lectus, gravida vitae ex sit amet, aliquam pharetra quam. Morbi aliquet varius dui quis condimentum. Mauris nec nibh mi. Vestibulum malesuada vestibulum metus, at semper magna porttitor vitae. Aenean nec risus ultricies lacus interdum tincidunt nec eget quam. Aenean non mollis dui, vitae varius ex. Nam cursus non sapien et tristique. Nulla facilisi. Phasellus sem sapien, facilisis sit amet ex a, porttitor suscipit ex. Vivamus sed libero dui. Sed enim enim, imperdiet quis tincidunt nec, pharetra ut eros. Morbi at sollicitudin nibh, eget luctus lorem.

Maecenas sodales erat non rhoncus tempus. Maecenas dictum diam eget mi elementum ullamcorper. Curabitur ac arcu nibh. Nullam vitae ligula lacinia, congue tortor nec, lobortis sapien. Suspendisse tincidunt libero orci, at laoreet erat tristique vel. Etiam odio tellus, pellentesque ut mollis vitae, condimentum non arcu. Nullam vulputate, augue nec ultricies consectetur, massa diam faucibus risus, eu feugiat ex sapien quis eros. Phasellus tempor mattis convallis. Aliquam blandit ipsum in aliquet interdum. Suspendisse at sapien erat.

Sed a tempus est. Sed maximus volutpat nibh, id commodo lectus. Vestibulum quis facilisis massa. Nam a dictum lectus. Fusce mauris nunc, scelerisque sed felis id, molestie laoreet enim. Curabitur non ante nec est efficitur congue in facilisis ante. Integer porta id mi vel tincidunt. Nam quis ligula suscipit risus volutpat sodales. Nullam id nulla metus. Cras ac mi bibendum, vehicula tellus eu, rutrum arcu. Duis ac malesuada purus. Nullam a nisl vel sapien euismod efficitur ac a nibh.

Nulla rutrum, nisl ac accumsan convallis, sem ipsum fringilla sem, et pretium lectus tellus id justo. Mauris gravida tristique est, vel tristique est viverra non. Cras nisl erat, tincidunt in eros ullamcorper, suscipit tempor risus. Mauris in commodo libero. Nunc ac sollicitudin ante. Nulla facilisi. Nam ac velit quis libero ultricies placerat. Nulla finibus enim nibh, ut ornare libero pulvinar et. Sed finibus feugiat ipsum, eget viverra justo mollis eget.

Vivamus neque est, gravida id ullamcorper nec, convallis a lorem. In pulvinar ex id orci mollis interdum. Quisque varius ullamcorper ligula a volutpat. Sed orci orci, aliquet nec imperdiet in, scelerisque non turpis. Praesent laoreet consectetur purus, sed laoreet est viverra eu. Suspendisse mattis, neque sed cursus efficitur, urna arcu elementum odio, sed lacinia purus enim sed libero. Suspendisse potenti. Donec suscipit velit velit, in vestibulum neque rhoncus in. Integer eu nisl ac felis dictum volutpat nec at dolor. Sed lacinia at diam ac eleifend. Duis facilisis libero sem, nec feugiat est venenatis vitae. Phasellus tempor volutpat enim vel iaculis. In hac habitasse platea dictumst.

Fusce semper congue nunc nec varius. Curabitur eu dui non neque vehicula vehicula. Fusce ultrices tellus non tristique tempus. Proin auctor libero ac placerat dapibus. Quisque ac posuere lectus, quis accumsan libero. Maecenas blandit tempor tempor. Nunc ornare, eros ac auctor tempor, nunc quam pharetra dui, in feugiat augue massa in nibh.

Fusce viverra tristique nisl eu efficitur. Phasellus consequat lorem tincidunt sem ultricies, a accumsan metus pellentesque. Proin velit dui, pellentesque ut enim in, volutpat fringilla lorem. Donec ultrices, nulla eleifend sollicitudin mollis, nisl lectus commodo nulla, id cursus risus nibh nec metus. Integer odio sapien, ultrices non tincidunt et, lobortis non tellus. In pellentesque ut eros quis lacinia. Nunc elit justo, lobortis et arcu nec, dignissim pulvinar dolor. Vivamus rutrum in leo quis ullamcorper. Donec in purus neque. Aenean convallis non augue a rutrum. Vestibulum convallis elit quis ligula lobortis facilisis. Nam et neque consectetur neque fringilla ornare a eget ligula. Donec nec mauris at massa scelerisque vulputate quis in ex. Vivamus massa eros, ullamcorper id ultrices porttitor, fringilla quis tortor. Pellentesque nec hendrerit massa, quis ultricies est. Praesent laoreet purus a neque pellentesque, sed convallis lacus laoreet.

Morbi sed sollicitudin leo. Sed elementum venenatis quam quis mattis. Duis ut dolor finibus, viverra mauris quis, porta lectus. In egestas ut metus dapibus placerat. Pellentesque ultrices diam bibendum velit dignissim ornare. Sed sollicitudin urna nisl, sed aliquam ipsum egestas sed. Cras fermentum odio quis felis mattis sollicitudin. Nulla convallis, urna sit amet convallis posuere, neque risus hendrerit enim, et sagittis orci magna sed enim. Morbi porta dui vitae magna volutpat molestie. Etiam imperdiet rutrum sapien ut sagittis. Morbi convallis lobortis mi, eget luctus orci. Nullam tempus metus quis laoreet blandit. Suspendisse metus nisi, accumsan et semper eget, pulvinar sed lorem.

Cras lobortis id mauris eu cursus. Sed eget libero urna. Morbi dictum sem mi, ac molestie arcu ullamcorper et. Integer sit amet finibus nunc. Mauris luctus odio id mauris ornare elementum. Donec in lacus et purus ultricies sodales nec eget mauris. Morbi egestas accumsan nunc, quis mollis tortor sagittis nec. Nam euismod diam in urna vulputate elementum. Morbi rhoncus nulla at ante cursus elementum. Sed ligula ante, tincidunt vitae ipsum id, ullamcorper pellentesque turpis.

Fusce dictum metus eget sollicitudin congue. Proin porttitor neque ac nisi tempor rutrum. Pellentesque semper turpis augue, vitae viverra nisi scelerisque vitae. Proin tristique pellentesque dui, eu venenatis felis posuere maximus. Nam lobortis aliquet mauris, eu luctus turpis varius sit amet. Aliquam tincidunt ultrices dui, sed pretium felis vehicula in. Aliquam pretium, purus quis bibendum facilisis, tortor libero iaculis massa, sit amet vestibulum turpis augue a elit. Praesent pulvinar, erat nec rhoncus viverra, nulla nulla ultrices erat, id facilisis risus enim a lacus. Phasellus ut iaculis est, a faucibus augue. Phasellus nec est at nunc pellentesque tempor vitae ac felis. In bibendum ultricies imperdiet. Etiam luctus lacinia nisl, condimentum tincidunt dolor venenatis quis.

Sed id efficitur neque, vel venenatis leo. Aliquam ut sodales elit. Pellentesque imperdiet eget libero ut sodales. Praesent bibendum odio ac lacus ullamcorper, nec tempus ex malesuada. Morbi id magna urna. Nulla ultricies eros ut faucibus lobortis. Vestibulum vitae erat augue. Nullam lacinia placerat turpis sed dapibus. Aliquam consectetur id ante quis molestie. Nunc eget ultricies ante. Aenean quis tellus euismod, ultricies arcu a, venenatis libero. Cras ut est tristique, rhoncus enim non, egestas tellus. Mauris sodales est in ex placerat lobortis quis et sapien. Nunc et tincidunt sapien. Aenean dignissim lacus justo, at maximus risus efficitur id.

Pellentesque magna risus, lacinia quis gravida at, cursus eu massa. Curabitur pharetra lacus ultrices diam pharetra, eu fringilla magna consectetur. Mauris sit amet malesuada elit, sit amet mattis magna. Sed mollis tristique luctus. Nam malesuada rhoncus justo sed vehicula. Praesent dictum massa orci, non congue dolor elementum at. Ut pulvinar condimentum elit, quis ultricies elit egestas quis. Sed at gravida leo, ut ultrices velit. Phasellus nec eros accumsan." > lorem_ipsum.txt
